### ISSUE TITLE
Add DSA as well

### ISSUE THREAD

**Issue by amritregmi26** [TechBastic/roadmaps#22]
Data Structure and Algorithms can not be missed while learning to code irrespective of the field. Can you please work on that too?

**Comment by amritregmi26** [comment]
I am working on it.

**Comment by adisuyash** [comment]
Yes we are working on it.
But if you wish to add it, go ahead

**Comment by amritregmi26** [comment]
I have sent a PR for DSA Courses @adisuyash

**Comment by adisuyash** [comment]
> I have sent a PR for DSA Courses @adisuyash

Please mention the issue number in the PR
